### ISSUE TITLE
Password in the repo

### ISSUE THREAD

**Issue by fizyk20** [KitN/IthkuilHelpBot#1]
The password to the bot's account is in the _ithkuilbot.py_ file, you should probably remove that ;)

**Comment by KitN** [comment]
Thanks, I've resolved that.

**Comment by fizyk20** [comment]
I hope you changed the password to the account as well, because it's still available in the repo history ;)

**Comment by KitN** [comment]
Yes, I did think of that. The password is different from the one in the history. Thank goodness no one tried to hijack it during the many months it was open for the taking!
